export { preAliasPlugin } from './plugins/preAlias'
export { cssPlugin, cssPostPlugin, isCSSRequest, isDirectCSSRequest } from './plugins/css'
export { assetPlugin } from './plugins/asset'
export { jsonPlugin } from './plugins/json'
export { definePlugin } from './plugins/define'
export { htmlInlineScriptProxyPlugin } from './plugins/html'
export { clientInjectionsPlugin } from './plugins/clientInjections'
export { esbuildPlugin, ESBuildOptions, transformWithEsbuild, ESBuildTransformResult } from './plugins/esbuild'
export { importAnalysisPlugin } from './plugins/importAnalysis';
export { ModuleGraph, ModuleNode } from './server/moduleGraph'
export { Plugin } from './plugin'
export { resolveBuildOptions } from './build'
export { ResolvedConfig, UserConfig, InlineConfig, sortUserPlugins, mergeConfig, mergeAlias } from './config'
export { createPluginContainer, PluginContainer } from './server/pluginContainer'
export { bareImportRE, isDataUrl, isExternalUrl, flattenId, injectQuery, fsPathFromId, removeImportQuery, unwrapId } from './utils'
export { DEFAULT_ASSETS_RE, DEFAULT_EXTENSIONS, CLIENT_ENTRY, ENV_ENTRY, CLIENT_PUBLIC_PATH, ENV_PUBLIC_PATH, CLIENT_DIR, FS_PREFIX } from './constants'
export { transformRequest,  TransformOptions,  TransformResult } from './server/transformRequest'
export { DepOptimizationOptions, DepOptimizationMetadata } from './optimizer'
export { scanImports } from './optimizer/scan'
export { ViteDevServer } from './server'
export { createDevHtmlTransformFn } from './server/middlewares/indexHtml';